import { OnInit, EventEmitter } from '@angular/core';
import { ApiService } from '../../../shared/services/api-service';
import { RecaptchaComponent } from 'ng-recaptcha';
import { CookieService } from '../../../core/cookie.service';
import { UserService } from '../../../shared/services/user-service';
import { NotificationService } from '../../../shared/services/notification.service';
import { TsLoginSignupService } from './ts-login-signup.service';
import { PlaceService } from '../../layout/components/ts-header/place.service';
export declare class TsLoginSignupComponent implements OnInit {
    apiService: ApiService;
    private cookieService;
    private userService;
    private notificationService;
    private tsLoginSignupService;
    private placeService;
    mode: any;
    defaultHeader: any;
    defaultSubHeader: any;
    rdurl: any;
    showSocial: any;
    closeDialog: EventEmitter<{}>;
    recaptchaRef: RecaptchaComponent;
    captchaToken: any;
    show: any;
    showPassword: any;
    isDefaultView: any;
    isSignInView: any;
    isSignUpView: any;
    isVerifyEmailView: any;
    showResetPassword: any;
    userTimezone: any;
    loginForm: any;
    captchaResponse: any;
    correctPhoneNumber: any;
    phoneError: any;
    socialLoginMsg: any;
    initializeTelInput: any;
    signInErrMessage: any;
    resetPwdLinkSent: boolean;
    signUpErrMessage: any;
    fbLoginURL: any;
    googleLoginURL: any;
    intlInput: any;
    showLoader: boolean;
    loaderText: any;
    countryCode: any;
    subObject: any;
    constructor(apiService: ApiService, cookieService: CookieService, userService: UserService, notificationService: NotificationService, tsLoginSignupService: TsLoginSignupService, placeService: PlaceService);
    ngOnInit(): void;
    ngOnDestroy(): void;
    initForm: () => void;
    close: () => void;
    clearErrors: () => void;
    resolve: (captchaResponse: string) => void;
    password: () => void;
    verifyEmail: () => Promise<any>;
    initializeIntlTelInput: () => void;
    validatePhoneNumber: () => void;
    signIn: () => Promise<any>;
    signUp: () => Promise<any>;
    forgotPassword: () => void;
    goBack: () => void;
    resetPassword: () => Promise<any>;
    randomString: (len: number, an: string) => string;
    resendVerifyEmail: () => Promise<any>;
    togglePasswordDisplay: () => void;
}
