import { OnInit, ElementRef } from '@angular/core';
import { Subject } from 'rxjs';
import { TimeService } from '../../../../../shared/services/time.service';
import { DatePipe } from '@angular/common';
import { Router } from '@angular/router';
import { PlaceService } from '../place.service';
export declare class SearchComponent implements OnInit {
    private placeService;
    private timeService;
    datepipe: DatePipe;
    algoliaIndexName: any;
    cityInput: ElementRef;
    citySuggestions: ElementRef;
    searchResultsEle: ElementRef;
    searchText: string;
    searchTextChanged: Subject<string>;
    searchActive: boolean;
    citySearchActive: boolean;
    cityPopupActive: boolean;
    placeSearchResults: any;
    searchResults: any;
    activePlace: any;
    cityQuery: string;
    cityQueryChanged: Subject<string>;
    activePlaceBackup: string;
    client: any;
    index: any;
    homeUrl: any;
    router: Router;
    host: any;
    popularPlaces: string[];
    constructor(placeService: PlaceService, timeService: TimeService, datepipe: DatePipe);
    callAlgolia: (text: any) => void;
    filterDataForSearchResult: (data: any) => void;
    clickout(event: any): void;
    navigateToListing: (interest: any) => void;
    navigateToEventPage: (eventCode: any) => void;
    search: (text: any) => void;
    ngOnInit(): void;
}
