import { OnInit } from '@angular/core';
import { MatDialog } from '@angular/material';
import { UserService } from './../../../../shared/services/user-service';
import { FooterService } from './ts-footer.service';
import { PlaceService } from '../ts-header/place.service';
export declare class TsFooterComponent implements OnInit {
    private dialog;
    private userService;
    private footerService;
    private placeService;
    city: any;
    placeId: any;
    source: any;
    popularEvents: any;
    recentBlogs: any;
    popularReads: any;
    popularCities: any;
    popularEventsData: any;
    countryCityMap: any;
    myBookingsURL: string;
    subObject: any;
    constructor(dialog: MatDialog, userService: UserService, footerService: FooterService, placeService: PlaceService);
    openContactUs: () => void;
    openMyBooking: () => void;
    redirectToMyBookings: () => void;
    openLogin: () => void;
    getCityFromCityCode: (code: string) => Promise<any>;
    getPopularEvents: () => Promise<any>;
    getPopularCities: () => Promise<any>;
    ngOnInit(): void;
    ngOnDestroy(): void;
}
