import { OnInit, ElementRef } from '@angular/core';
import { MatDialog } from '@angular/material/dialog';
import { UserService } from '../../../../shared/services/user-service';
import { PlaceService } from './place.service';
import { HeaderService } from './ts-header.service';
import { UtilityService } from '../../../../shared/services/utilities.service';
export declare class TsHeaderComponent implements OnInit {
    private utilityService;
    private headerService;
    private placeService;
    private dialog;
    private userService;
    Components: Array<String>;
    backState: boolean;
    source: string;
    searchText: string;
    citySuggestions: ElementRef;
    userMenuEle: ElementRef;
    user: any;
    router: any;
    urlArray: any;
    userMenu: any;
    host: string;
    activePlace: string;
    activeCity: string;
    activeCountryCode: string;
    homePageUrl: string;
    s3BucketUrl: any;
    cityPopupActive: boolean;
    popularPlaces: any;
    constructor(utilityService: UtilityService, headerService: HeaderService, placeService: PlaceService, dialog: MatDialog, userService: UserService);
    buildUrlArray: () => void;
    clickout: (event: any) => void;
    openLogin: (callback?: any) => void;
    navigateToDashboard: () => void;
    createEventClick: () => void;
    navigateToMobileSearch: () => void;
    openMyProfileComponent: () => void;
    closeMyProfile: (event: any) => void;
    goBack: () => void;
    goToHomePage: () => void;
    getPopularPlaces: () => Promise<void>;
    ngOnInit(): void;
}
